version: '3.9'

services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sot-workbench
      - POSTGRES_USER=sot
      - POSTGRES_PASSWORD=sot

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
